// External AI policy hook.
// Replace this file with the policy generated by the other AI.

function pickMove(state, legalActions) {
  if (!Array.isArray(legalActions) || legalActions.length === 0) return null;

  // Default fallback (replace with your real strategy): pick random legal action.
  return legalActions[Math.floor(Math.random() * legalActions.length)];
}

module.exports = { pickMove };
