// External AI policy hook. Replace with policy generated by the other AI.
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.GoFishPolicies = root.GoFishPolicies || {};
  root.GoFishPolicies.otherai = api;
})(typeof self !== "undefined" ? self : this, function () {
  function pickMove(state, legalActions) {
    if (!Array.isArray(legalActions) || legalActions.length === 0) return null;
    return legalActions[Math.floor(Math.random() * legalActions.length)];
  }

  return { pickMove };
});
